spring.datasource.url=jdbc:postgresql://localhost:5432/Coursework_3_TelegrommBot
spring.datasource.username=student
spring.datasource.password=chocolatefrog
telegram.bot.token=8459765123:AAHeJ5UErI8JTfJixbA7Nk8bfuaja16LZxs
telegram.bot.username=HomeWorkGoBot
server.port=8081